# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9283862a6341f0c01e3362fd1193de9658f9a2d3791fd4163fb37fd7bab276da69479be4c76a6f0bcaf132460cf2c187fd2ba897c3a664ae4e79dcd3bdf0812

test:
  secret_key_base: 3bfeb83b40b0f885a0244509862c4743d564d29aa0b91dbcb3eb27d5bffb13105cd363b183f11d4a90eb6ba908389e8d9e9b0b4f6c28201d1f9d5ad2919a292f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
